import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Header from '@/components/Header';
import AsideNav from '@/components/AsideNav';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Games Hub',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <main>
                    <section className="grid grid-cols-4 p-8">
                        <div className="hidden md:flex">
                            <AsideNav />
                        </div>
                        {children}
                    </section>
                </main>
            </body>
        </html>
    );
}
